select FL_FLIGHT_NO, DEP_DEP_DATE
from FLIGHT, EQUIP_TYPE, DEPARTURES
where DEP_EQUIP_NO = EQ_EQUIP_NO
and DEP_FLIGHT_NO = FL_FLIGHT_NO
and EQ_EQUIP_TYPE not like 'BOE%'
order by DEP_DEP_DATE asc, DEP_FLIGHT_NO desc
;
